[package]
name = "claimdag"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description.workspace = true
readme.workspace = true

[package.metadata.binstall]
pkg-url = "{ repo }/releases/download/v{ version }/claimdag-v{ version }-{ target }.tar.gz"
bin-dir = "claimdag-v{ version }-{ target }/claimdag{ binary-ext }"
pkg-fmt = "tgz"

[dependencies]
xxhash-rust.workspace = true
capnp.workspace = true
memmap2.workspace = true
libc = "0.2"

[dev-dependencies]
criterion = { version = "0.5", default-features = false }

[[bench]]
name = "ready"
harness = false
